import type {Metadata} from "next";
import React from "react";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center p-4 bg-[linear-gradient(135deg,#f6f4f5_50%,#ff7a00_50%)]">
            <Link href="/">
                <Image
                    src="/logo.png"
                    width={150}
                    height={150}
                    alt="logo"
                    className="mx-auto"
                    priority
                />
            </Link>
            <div className="w-full max-w-sm bg-white p-6 shadow-md shadow-primary rounded-lg">
                {children}
            </div>
        </div>
    );
}
